Ext.define('app.model.schemas.Room', {
    extend: 'app.model.schemas.Base',
    mapping: 'org.takeback.chat.entity.GcRoom',
    name: '房间',
    orderInfo: 'hot desc',
    height:450,
    columnCount:4,
    items: [
        {id: 'id', type: 'string', name: 'ID(唯一不可重复)',allowBlank:false, display:0},
        {id: 'name', type: 'string', name: '房间名称',allowBlank:false,queryable:true},
        {id: 'catalog', type: 'string', name: '房间分类',allowBlank:false,dic:'dic.chat.roomCata'},
        {id: 'type', type: 'string', name: '游戏类型',allowBlank:false,dic:'dic.chat.gameType'},
        {id: 'owner', type: 'string',defaultValue:'0',value:'0',allowBlank:false, name: '房主(ID) 默认为0 为系统平台'},
        {id: 'limitNum', type: 'int',allowBlank:false, name: '人数限制'},
        {id: 'createtype', type: 'string',defaultValue:'0',value:'0',allowBlank:false, name: '创建来源 0系统 1玩家自助'},
        {id: 'shareRate', type: 'int', name: '分成比例'},
        {id: 'sumPool', type: 'double', name: '奖池金额'},
        {id: 'poolAdd', type: 'double', name: '单次累奖'},
        {id: 'feeAdd', type: 'double',defaultValue:'0',value:'0', allowBlank:false,name: '单次服务费(接龙是具体金额，牛牛G22为每包服务金额，扫雷是提取比例不大于1)'},
        {id: 'sumFee', type: 'double', name: '服务费总数',readOnly:true},
        {id: 'sumPack', type: 'int', name: '发包总数',readOnly:true},
        {id: 'hot', type: 'int', name: '排序'},
        {id: 'unDead', type: 'int', name: '免死账号'},
        {id: 'intialnum', type: 'int',defaultValue:'0',value:'0', name: '虚拟在线人数'},
        {id: 'addedSleep', type: 'int',defaultValue:'0', value:'0',allowBlank:false,name: '机器人递延操作秒，根据设置机器人多少调整'},
        {id: 'robotTimeout', type: 'int',defaultValue:'0', value:'0',allowBlank:false,name: '机器人抢包最低间隔(毫秒)0不处理'},
        {id: 'roomimg', type: 'string', name: '图标',dic:'dic.chat.roomLogo'},
        {id: 'psw', type: 'string', name: '密码'},
        //{id: 'createdate', type: 'datetime', name: '创建时间'},
        {id: 'status', type: 'string', defaultValue:'0',value:'0',allowBlank:false,name: '状态(运行中勿修改)',dic:'dic.chat.roomStatus'},
        {id: 'issyscontrol', type: 'string', defaultValue:'1',value:'1',allowBlank:false,name: '赢率控制是否基于通用系统配置（是通用配置 否基于本房间 ）',dic:'dic.yesno'},
        
        {id: 'controldefaultrate', type: 'string',defaultValue:'20',value:'20',allowBlank:false, name: '基准赢率(%)（不大于100的数值）'},
        {id: 'controlkill', type: 'string',defaultValue:'10',value:'10',allowBlank:false, name: '控制赢率(%)（0-100）超过基准赢率的距离,例如超过基准赢率10% 开始添加输的点数'},
        {id: 'controlsave', type: 'string',defaultValue:'10',value:'10',allowBlank:false, name: '控制输率(%)（0-100）低于基准赢率的距离,例如低于基准赢率10% 开始添加赢的点数'},
         
        {id: 'description', type: 'string', name: '简介',width:"280"},
        {id: 'detail', type: 'string', name: '详细说明',width:"280",colspan:"4",xType: 'htmleditor'},
    ],
    singleton: true
});